In [6]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
x=np.where(arr==6)
print(x,arr.dtype)

(array([1, 4]),) int64


In [7]:
x1=np.where(arr%2==0)
print(x1)

(array([1, 2, 4, 5]),)


In [8]:
arr=np.array([0,1,2,2,7,8,9])
x2=np.searchsorted(arr,3,side='left')
print(x2)

4


In [ ]:
arr=np.array([0,1,5,3,6,7,2])
x1=np.searchsorted(arr,3,side='left')
print(x1)

2


In [9]:
x3=np.searchsorted(arr,8,side='right')
print(x3)

6


In [10]:
arr=np.array([9,5,2,7,6,4])
print(np.sort(arr))

[2 4 5 6 7 9]


In [11]:
arr=np.array([[7,4,9],[9,1,4]])
print(np.sort(arr))

[[4 7 9]
 [1 4 9]]


In [12]:
arr=np.array([51,78,68,88])
x=[False,True,True,False]
filter_arr=arr>70
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True]
[78 88]
