In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print("one diminisional array",a)

one diminisional array [1 2 3 4 5]


In [5]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print("two diminisional array",b)

two diminisional array [[1 2 3 4]
 [5 6 7 8]]


In [7]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
d=np.random.random((3,3))
print(d)

[[0.29677918 0.9639252  0.90494318]
 [0.35021564 0.33655966 0.88064004]
 [0.39844239 0.18599016 0.07545561]]


In [11]:
e=np.arange(0,30,5)
print(e)

[ 0  5 10 15 20 25]


In [3]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr=arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [4]:
import numpy as np
flat=arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [6]:
print(arr.shape)

(3, 4)


In [12]:
print(arr.ndim)

2


In [9]:
print(arr.size)

12


In [11]:
print(arr.dtype)

int64


In [6]:
import numpy as np
arr=np.array([[1,2,3,4],[10,20,30,40],[11,22,33,44]])
newtype=arr.astype('f')
print("\n convert array \n",newtype)
print("\n converted array type : arr.dtype")
size=len(arr)
print("\n size of array : \n",size)



 convert array 
 [[ 1.  2.  3.  4.]
 [10. 20. 30. 40.]
 [11. 22. 33. 44.]]

 converted array type : arr.dtype

 size of array : 
 3
