In [17]:
import numpy as np
arr1=[20,40,50,70,10]
arr2=[6,2,9,7,1]
a=np.array(arr1)
b=np.array(arr2)
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[20 40 50 70 10]
[6 2 9 7 1]
[26 42 59 77 11]
[14 38 41 63  9]
[120  80 450 490  10]
[ 3.33333333 20.          5.55555556 10.         10.        ]


In [18]:
print(a.dot(b))
sclr=3
print("sclar value:",sclr)
print("array:",a)
print("result:",a*sclr)

1150
sclar value: 3
array: [20 40 50 70 10]
result: [ 60 120 150 210  30]


In [19]:
import numpy as np
a=np.array([[10,20],[30,40]])
b=np.array([[3,7],[5,9]])
print(a%b)

[[1 6]
 [0 4]]


In [20]:
def my_func(X,Y):
    if X>Y:
        return X-Y
    else:
        return X+Y
arr1=[10,7,2]
arr2=[6,5,3]
vect_func=np.vectorize(my_func)
print("array:",arr1)
print("array:",arr2)
print("result:",vect_func(arr1,arr2))

array: [10, 7, 2]
array: [6, 5, 3]
result: [4 2 5]
